### PR TITLE
:sparkles: IOT project

### PR DESCRIPTION
**Pull request by TheNoobProgrammeur**
IoT Part 

Author : Antoine BERTHIER

### CODE REVIEW

**Review by beaussan — COMMENTED** [review]
Don't forget it's in English =)

**Comment by TheNoobProgrammeur** [comment]
> 
> 
> Don't forget it's in English =)

It is on WIP. I have Path bp (Win ....)  so I do MR for preview.

**Comment by TheNoobProgrammeur** [comment]
@beaussan  I have finished my part

**Review by beaussan — APPROVED** [review]

**Comment by beaussan** [comment]
@all-contributors please add @TheNoobProgrammeur for ideas, doc

**Pull request merged**
