### PR TITLE
Push report Equistrian park manager 

### PR DESCRIPTION
**Pull request by BBR2394**
A pull request for my report of equestrian park manager (that i called horse manager system )

### CODE REVIEW

**Review by beaussan — CHANGES_REQUESTED** [review]
It doesn't compile :(

**Comment by beaussan** [comment]
Also, please rebase on the main repo

**Comment by BBR2394** [comment]
Normally, I have rebase, but I am not sure ^^

**Review by BBR2394 — COMMENTED** [review]
I put some </br> instead of <br/> (of just <br>) and it doesn't like it ...

**Comment by beaussan** [comment]
@all-contributors please add @BBR2394 for ideas, doc

**Pull request merged**
