### PR TITLE
Feat/rogue like clicker

### PR DESCRIPTION
**Pull request by Unknow46**
Hello Nicolas, i'm sorry to be late to ask for my merge request 😓

### CODE REVIEW

**Comment by beaussan** [comment]
Hey, don't worry, you are the second to submit your pr :)

**Comment by beaussan** [comment]
@all-contributors please add @Unknow46 for ideas, doc

**Comment by beaussan** [comment]
@all-contributors please add @Unknow46 for ideas, doc

**Comment by beaussan** [comment]
@Unknow46 did you include the url of the source code ?

**Comment by Unknow46** [comment]
> @Unknow46 did you include the url of the source code ?

Yes i did, it's at the end of my documentation with the link to my APK

**Comment by beaussan** [comment]
Thanks ! I wasn't sure you put it :)

**Comment by Unknow46** [comment]
> Thanks ! I wasn't sure you put it :)

No problem 😁

**Pull request merged**
